from __future__ import annotations


class LLMCoreErrorCode:
    MODEL_NOT_FOUND = "LLM_MODEL_NOT_FOUND"
    PROVIDER_UNSUPPORTED = "LLM_PROVIDER_UNSUPPORTED"
    PROVIDER_DEPENDENCY_MISSING = "LLM_PROVIDER_DEPENDENCY_MISSING"
    API_KEY_MISSING = "LLM_API_KEY_MISSING"
    REQUEST_FAILED = "LLM_REQUEST_FAILED"
    RESPONSE_INVALID = "LLM_RESPONSE_INVALID"
