from __future__ import annotations


class LLMCoreErrorCode:
    MODEL_NOT_FOUND = "LLM_MODEL_NOT_FOUND"
    PROVIDER_UNAVAILABLE = "LLM_PROVIDER_UNAVAILABLE"
    PROVIDER_UNCONFIGURED = "LLM_PROVIDER_UNCONFIGURED"
    PROVIDER_ERROR = "LLM_PROVIDER_ERROR"
    PROVIDER_RESULT_INVALID = "LLM_PROVIDER_RESULT_INVALID"
    CONFIG_INVALID = "LLM_CONFIG_INVALID"
    PROVIDER_UNSUPPORTED = "LLM_PROVIDER_UNSUPPORTED"
    PROVIDER_DEPENDENCY_MISSING = "LLM_PROVIDER_DEPENDENCY_MISSING"
    API_KEY_MISSING = "LLM_API_KEY_MISSING"
    REQUEST_FAILED = "LLM_PROVIDER_REQUEST_FAILED"
    RESPONSE_INVALID = "LLM_RESPONSE_INVALID"
    RESPONSE_JSON_INVALID = "LLM_RESPONSE_JSON_INVALID"
    TIMEOUT = "LLM_TIMEOUT"
    CANCELLED = "LLM_CANCELLED"
    EMBED_UNSUPPORTED = "LLM_EMBED_UNSUPPORTED"
