from __future__ import annotations

AGENT_ID_REQUIRED = "AGENT_ID_REQUIRED"
AGENT_NOT_FOUND = "AGENT_NOT_FOUND"
AGENT_ALREADY_EXISTS = "AGENT_ALREADY_EXISTS"
AGENT_NOT_RUNNABLE = "AGENT_NOT_RUNNABLE"
AGENT_SUSPENDED = "AGENT_SUSPENDED"
AGENT_KILL_REQUESTED = "AGENT_KILL_REQUESTED"
AGENT_TERMINAL = "AGENT_TERMINAL"
AGENT_REAPED = "AGENT_REAPED"
AGENT_TRANSITION_INVALID = "AGENT_TRANSITION_INVALID"
AGENT_REAP_FORBIDDEN = "AGENT_REAP_FORBIDDEN"
AGENT_HAS_ACTIVE_SYSCALLS = "AGENT_HAS_ACTIVE_SYSCALLS"
AGENT_CLEANUP_INCOMPLETE = "AGENT_CLEANUP_INCOMPLETE"
AGENT_RESOURCE_RELEASE_FAILED = "AGENT_RESOURCE_RELEASE_FAILED"
AGENT_SYSCALL_HELD = "AGENT_SYSCALL_HELD"
AGENT_SYSCALL_CANCELLED = "AGENT_SYSCALL_CANCELLED"
AGENT_CRASHED = "AGENT_CRASHED"
AGENT_KILLED = "AGENT_KILLED"


class AgentLifecycleError(RuntimeError):
    def __init__(self, error_code: str, reason: str = "") -> None:
        self.error_code = error_code
        self.reason = reason or error_code
        super().__init__(self.reason)
