from __future__ import annotations

from typing import Any, Protocol


class RosBridgeClient(Protocol):
    async def resolve_place(self, name: str) -> dict[str, Any]: ...

    async def get_robot_state(self) -> dict[str, Any]: ...

    async def check_safety(self, skill_name: str, args: dict[str, Any], app_id: str) -> dict[str, Any]: ...

    async def navigate_to(self, place: str, timeout_s: int, cancel_event=None) -> dict[str, Any]: ...

    async def inspect_area(self, place: str, timeout_s: int) -> dict[str, Any]: ...

    async def stop_robot(self, reason: str) -> dict[str, Any]: ...

    async def ask_human(self, question: str, options=None, timeout_s: int = 60, require_confirmation: bool = False) -> dict[str, Any]: ...

    async def report_say(self, message: str) -> dict[str, Any]: ...
